#!/usr/bin/env bash
#
# pull-dotnet.sh — vendor dotnet/runtime's src/libraries into RubyC projects.
#
# Standalone (git + coreutils only; no dotnet SDK required). Re-runnable:
#   * first run  -> blobless sparse clone of dotnet/runtime (src/libraries only)
#   * later runs -> git fetch (update-checking friendly) + regenerate projects
#
# The vendored tree keeps upstream .cs files byte-for-byte (git-clean, so
# `git log` / `git diff` / `git pull` detect upstream upgrades). Each generated
# <Lib>.rcp copies .cs -> .rc in its pre-build hook and deletes the .rc copies
# in its post-build hook, so the compiler builds native .rc while the tree
# stays in its upstream .cs form at all times.
#
# Usage:
#   tools/pull-dotnet.sh                          # clone/update + regenerate all
#   RUBYC_DOTNET_BRANCH=release/9.0 tools/pull-dotnet.sh
#   RUBYC_DOTNET_DEPTH=500 tools/pull-dotnet.sh   # deeper history for diffing
#
set -euo pipefail

URL="${RUBYC_DOTNET_URL:-https://github.com/dotnet/runtime.git}"
BRANCH="${RUBYC_DOTNET_BRANCH:-main}"
DEPTH="${RUBYC_DOTNET_DEPTH:-200}"
SRC_REL="src/libraries"
# System.Private.CoreLib also compiles its CoreCLR-VM partials
# (`String.CoreCLR.cs` with `FastAllocateString`, `Enum.CoreCLR.cs`
# with `GetEnumInfo`, `Array.CoreCLR.cs` with `Rank`, ...): without
# these, CoreLib sources reference undeclared members. Pulled
# alongside the libraries; only CoreLib's build consumes them.
CORECLR_REL="src/coreclr/System.Private.CoreLib/src"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEST="$ROOT/dotnet-runtime"
LIBS_DIR="$DEST/$SRC_REL"
SOLUTION="$LIBS_DIR/dotnet-runtime.rcs"
HOOKS_HELPER="$LIBS_DIR/rc-hooks.sh"

log() { printf '\033[1;34[pull\033[0m %s\n' "$*"; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v git >/dev/null 2>&1 || die "git is required"

# ---------- 1. clone or update ----------
if [ -d "$DEST/.git" ]; then
  log "updating existing clone at $DEST"
  git -C "$DEST" fetch --depth "$DEPTH" origin "$BRANCH"
  git -C "$DEST" sparse-checkout set "$SRC_REL" "$CORECLR_REL"
  git -C "$DEST" checkout "$BRANCH"
  git -C "$DEST" merge --ff-only "origin/$BRANCH"
else
  log "cloning $URL (branch=$BRANCH depth=$DEPTH sparse=$SRC_REL,$CORECLR_REL)"
  [ -e "$DEST" ] && die "$DEST exists but is not a git clone; remove it first"
  git clone --filter=blob:none --no-checkout --depth "$DEPTH" --sparse "$URL" "$DEST"
  git -C "$DEST" sparse-checkout set "$SRC_REL" "$CORECLR_REL"
  git -C "$DEST" checkout "$BRANCH"
fi
SHA="$(git -C "$DEST" rev-parse --short HEAD)"
log "at $BRANCH @ $SHA"

# ---------- 2. keep the clone pristine for update-checking ----------
# Ignore the generated project files via the per-repo local exclude list
# (.git/info/exclude): it is never committed, never pushed, and never touches
# a tracked file, so `git status`/`git diff`/`git log`/`git pull` stay clean
# for detecting upstream dotnet/runtime upgrades.
EXCLUDE="$DEST/.git/info/exclude"
marker="# RubyC generated project files (local-only ignore)"
if grep -qF "$marker" "$EXCLUDE" 2>/dev/null; then
  : # already present
else
  {
    printf '\n%s\n' "$marker"
    printf 'src/libraries/**/*.rcp\n'
    printf 'src/libraries/**/*.rcs\n'
    printf 'src/libraries/rc-hooks.sh\n'
    printf 'src/libraries/**/*.rc\n'
  } >> "$EXCLUDE"
fi

# ---------- 3. shared build-hooks helper ----------
# Lives at src/libraries/rc-hooks.sh; each <Lib>.rcp calls it as ../rc-hooks.sh
# (run with CWD = the project dir, i.e. src/libraries/<Lib>/).
cat > "$HOOKS_HELPER" <<'HOOKS'
#!/usr/bin/env bash
# Build hooks for pulled dotnet/runtime libraries (generated by pull-dotnet.sh).
# Invoked by the .rcp as:
#   bash ../rc-hooks.sh prebuild src
#   bash ../rc-hooks.sh postbuild <Lib> src
# with CWD = the project directory (src/libraries/<Lib>/).
set -euo pipefail

cmd="${1:?usage: rc-hooks.sh prebuild|postbuild <arg>...}"
shift

case "$cmd" in
  prebuild)
    srcdir="${1:-src}"
    # Drop the previous build's output dir first: post-build installs
    # from `out/` on success, but on failure a stale artifact would
    # otherwise be re-installed by a later post-build, masking the
    # failure with a fresh timestamp on stale bytes.
    rm -rf out
    # Copy upstream .cs -> .rc (transient build sources). The .cs files are
    # never modified, so the vendored tree stays git-clean against
    # dotnet/runtime even mid-build.
    find "$srcdir" -name '*.cs' ! -path '*/obj/*' ! -path '*/bin/*' -print0 \
      | while IFS= read -r -d '' f; do cp -- "$f" "${f%.cs}.rc"; done
    # CoreCLR-VM partials (`src/coreclr/System.Private.CoreLib/src/`,
    # e.g. `String.CoreCLR.cs`): only System.Private.CoreLib compiles
    # them (they extend its `partial` types). Fetched as transient
    # `.rc` under src/CoreCLR/, so the normal glob picks them up
    # and post-build cleanup removes them.
    if [ "$(basename "$PWD")" = "System.Private.CoreLib" ]; then
      coredir="../../../src/coreclr/System.Private.CoreLib/src"
      if [ -d "$coredir" ]; then
        (cd "$coredir" && find . -name '*.cs' ! -path '*/obj/*' ! -path '*/bin/*' -print0) \
          | while IFS= read -r -d '' f; do
          dest="$srcdir/CoreCLR/${f#./}"
          dest="${dest%.cs}.rc"
          mkdir -p "$(dirname "$dest")"
          cp -- "$coredir/$f" "$dest"
        done
      else
        # Sparse checkout (no src/coreclr in tree): restage the masters
        # from the in-repo cache (tools/coreclr-masters, via
        # tools/stage_coreclr.sh; $RUBYC_STAGE_CORECLR overrides).
        # Every build restages: post-build deletes the transient .rc
        # files, and downstream closures recompile CoreLib sources, so
        # the CoreCLR halves must be present every time, not just at
        # pull time. Fail loudly when nothing stages (a silent miss
        # surfaces hundreds of phantom unknown-member errors later).
        stage="${RUBYC_STAGE_CORECLR:-../../../../tools/stage_coreclr.sh}"
        if [ -f "$stage" ]; then
          bash "$stage" "$srcdir"
          if [ -z "$(find "$srcdir/CoreCLR" -name '*.rc' -print -quit 2>/dev/null)" ]; then
            echo "[rubyc] error: CoreCLR masters staging produced no files" >&2
            exit 1
          fi
        else
          echo "[rubyc] warning: no CoreCLR masters (expected $coredir or $stage)" >&2
        fi
      fi
    fi
    # Drop sources the csproj excludes on non-listed platforms: a
    # <Compile Include="F" Condition="..."> positively requiring a
    # non-Linux TargetPlatformIdentifier (windows, android, ios,
    # browser, ...) never belongs in a linux build — such files carry
    # `#error Unknown target`-style guards that would otherwise fail
    # the build. Libraries also set <EnableDefaultItems>false</
    # EnableDefaultItems>, so staged sources with no explicit entry
    # at all (e.g. an unlisted other-target alternative duplicating a
    # listed file's types) are dropped too. Only certain-foreign
    # conditions exclude; everything else keeps the file. Needs
    # python3; without it this step is skipped (previous behavior).
    if command -v python3 >/dev/null 2>&1; then
      find "$srcdir" -maxdepth 2 \( -name '*.csproj' -o -name '*.projitems' \) ! -path '*/obj/*' ! -path '*/bin/*' -print0 \
        | while IFS= read -r -d '' proj; do
        projdir=$(dirname "$proj")
        # Target triple selected by the driver (RUBYC_TARGET, e.g.
        # linux_x86_64; empty when none was selected): drives the
        # dotnet-style platform taxonomy below (same hook, different
        # files per target OS). Only linux_x86_64 exists as a RubyC
        # target today; the other branches light up with future targets.
        target_triple="${RUBYC_TARGET:-linux_x86_64}"
        case "$target_triple" in
          windows-*)
            export RUBYC_TPI="windows" RUBYC_TARGETS_WINDOWS="true"
            export RUBYC_TARGETS_LINUX="" RUBYC_TARGETS_UNIX=""
            export RUBYC_USE_OPENSSL="" RUBYC_USE_APPLE_CRYPTO="" RUBYC_USE_ANDROID_CRYPTO=""
            ;;
          macos-*|osx-*|*macos*)
            export RUBYC_TPI="osx" RUBYC_TARGETS_UNIX="true" RUBYC_TARGETS_OSX="true"
            export RUBYC_TARGETS_LINUX="" RUBYC_TARGETS_WINDOWS=""
            export RUBYC_USE_OPENSSL="" RUBYC_USE_APPLE_CRYPTO="true" RUBYC_USE_ANDROID_CRYPTO=""
            ;;
          *android*)
            export RUBYC_TPI="android" RUBYC_TARGETS_UNIX="true" RUBYC_TARGETS_ANDROID="true"
            export RUBYC_TARGETS_LINUX="" RUBYC_TARGETS_WINDOWS=""
            export RUBYC_USE_OPENSSL="" RUBYC_USE_APPLE_CRYPTO="" RUBYC_USE_ANDROID_CRYPTO="true"
            ;;
          *browser*)
            export RUBYC_TPI="browser" RUBYC_TARGETS_UNIX="true" RUBYC_TARGETS_BROWSER="true"
            export RUBYC_TARGETS_LINUX="" RUBYC_TARGETS_WINDOWS=""
            export RUBYC_USE_OPENSSL="" RUBYC_USE_APPLE_CRYPTO="" RUBYC_USE_ANDROID_CRYPTO=""
            ;;
          *wasi*)
            export RUBYC_TPI="wasi" RUBYC_TARGETS_UNIX="true" RUBYC_TARGETS_WASI="true"
            export RUBYC_TARGETS_LINUX="" RUBYC_TARGETS_WINDOWS=""
            export RUBYC_USE_OPENSSL="" RUBYC_USE_APPLE_CRYPTO="" RUBYC_USE_ANDROID_CRYPTO=""
            ;;
          *)
            export RUBYC_TPI="unix" RUBYC_TARGETS_LINUX="true" RUBYC_TARGETS_UNIX="true"
            export RUBYC_TARGETS_WINDOWS=""
            export RUBYC_USE_OPENSSL="true" RUBYC_USE_APPLE_CRYPTO="" RUBYC_USE_ANDROID_CRYPTO=""
            ;;
        esac
        python3 - "$proj" "$projdir" "$srcdir" <<'PYEOF' || true
import os, sys, re, xml.etree.ElementTree as ET
# Platform truth for a standard linux-x64 CoreCLR build (non-AOT,
# full globalization, release). Everything else is empty.
# Target-selected values arrive via RUBYC_TPI/RUBYC_TARGETS_* (set
# above from the driver's RUBYC_TARGET triple); the fallbacks preserve
# Linux behavior when unset.
KNOWN = {
    # linux-x64 note: upstream TargetPlatformIdentifier taxonomy maps
    # Linux (and other Unix-likes without their own token) to 'unix'
    # (macOS is 'osx'); 'linux' here would wrongly exclude every
    # `'$(TargetPlatformIdentifier)' == 'unix'` group (e.g.
    # ConsolePal.Unix.cs, which has no Linux-specific alternative).
    'TargetPlatformIdentifier': os.environ.get('RUBYC_TPI', 'unix'),
    'TargetFrameworkIdentifier': '.NETCoreApp',
    'TargetsLinux': os.environ.get('RUBYC_TARGETS_LINUX', 'true'),
    'TargetsUnix': os.environ.get('RUBYC_TARGETS_UNIX', 'true'),
    'TargetsWindows': os.environ.get('RUBYC_TARGETS_WINDOWS', ''),
    'TargetsOSX': os.environ.get('RUBYC_TARGETS_OSX', ''),
    'TargetsAndroid': os.environ.get('RUBYC_TARGETS_ANDROID', ''),
    'TargetsBrowser': os.environ.get('RUBYC_TARGETS_BROWSER', ''),
    'TargetsWasi': os.environ.get('RUBYC_TARGETS_WASI', ''),
    # Crypto backends are OS-selected upstream (OpenSSL on Linux,
    # SecureTransport on Apple, AndroidCrypto on Android, CNG on
    # Windows): Linux-first default, triple-overridden above.
    'UseOpenSsl': os.environ.get('RUBYC_USE_OPENSSL', 'true'),
    'UseAppleCrypto': os.environ.get('RUBYC_USE_APPLE_CRYPTO', ''),
    'UseAndroidCrypto': os.environ.get('RUBYC_USE_ANDROID_CRYPTO', ''),
    'Is64Bit': 'true',
    'FeatureComWrappers': 'true',
    'FeatureCoreCLR': 'true',
    'FeatureCrossProcessMutex': 'true',
    'FeatureMultithreading': 'true',
    'FeaturePerfTracing': 'true',
    'FeaturePortableThreadPool': 'true',
    'FeaturePortableTimer': 'true',
    'FeatureXplatEventSource': 'true',
}
def expand(s):
    return re.sub(r'\$\(([^)]+)\)', lambda m: KNOWN.get(m.group(1), ''), s)
def eval_atom(atom):
    m = re.match(r"^\s*'(.*)'\s*(==|!=)\s*'(.*)'\s*$", atom)
    if not m:
        return True  # unknown shape (functions, etc.): keep the file
    raw_a, op, raw_b = m.group(1), m.group(2), m.group(3)
    a, b = expand(raw_a), expand(raw_b)
    # Platform family: `'unix'` groups AND `'linux'` groups both belong
    # in a Linux build (likewise `'unix'`+`'osx'` on macOS) — a scalar
    # TPI cannot equal both, so compare set membership instead. Proven
    # necessary both ways: ConsolePal.Unix.cs has no Linux alternative,
    # and NetworkInformation's `.Linux.cs` PALs have no Unix one
    # (`.UnknownUnix.cs` is illumos-only); collisions are all `partial`
    # merges. Other platforms keep scalar behavior.
    tpi = os.environ.get('RUBYC_TPI', 'unix')
    family = {'unix': ('unix', 'linux'), 'linux': ('unix', 'linux'),
              'osx': ('unix', 'osx')}.get(tpi)
    if family is not None and 'TargetPlatformIdentifier' in (raw_a + raw_b):
        lit = b if 'TargetPlatformIdentifier' in raw_a else a
        if lit == '':
            # Agnostic (`== ''`) belongs everywhere; negated
            # (`!= ''`, "a platform is set") is likewise true.
            return True
        eq = lit in family
        return eq if op == '==' else (not eq)
    eq = (a == b)
    return eq if op == '==' else (not eq)
def strip_outer(cond):
    # Remove one balanced outer paren layer, repeatedly: (A) -> A.
    # Bails (returns as-is) unless the first '(' matches the last ')'.
    while len(cond) >= 2 and cond[0] == '(' and cond[-1] == ')':
        depth = 0
        ok = True
        for i, ch in enumerate(cond):
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
                if depth == 0 and i != len(cond) - 1:
                    ok = False
                    break
        if not ok or depth != 0:
            break
        cond = cond[1:-1].strip()
    return cond
def eval_cond(cond):
    # Recursive descent over top-level operators (OR lowest precedence,
    # so it splits first): AND binds tighter, and parenthesized groups
    # from combine_conds (`(A And B) And (C Or D)`) evaluate inside-out.
    # A flat regex split mis-evaluates nested groups (it once dropped
    # Unix files by reducing `(A And B) And (C Or D)` to garbage atoms).
    cond = strip_outer(cond.strip())
    or_parts = split_top(cond, 'or')
    if len(or_parts) > 1:
        return any(eval_cond(p) for p in or_parts)
    and_parts = split_top(cond, 'and')
    if len(and_parts) > 1:
        return all(eval_cond(p) for p in and_parts)
    return eval_atom(cond)
def split_top(cond, keyword):
    # Split on a Boolean operator only at paren-depth zero and outside
    # single quotes: `$(...)` property expansions contain parens, and
    # combine_conds emits parenthesized groups (`(A) And (B)`). A naive
    # regex split breaks both (it once let OSX-only files into Linux
    # builds by splitting `(OSX or MacCat) And (Unix)` on the inner
    # `or`). Operator match is case-insensitive, whitespace-bounded
    # (MSBuild style).
    parts, depth, cur, in_quote, i = [], 0, [], False, 0
    n, kw = len(cond), keyword.lower()
    while i < n:
        ch = cond[i]
        if ch == "'":
            in_quote = not in_quote
            cur.append(ch)
            i += 1
            continue
        if not in_quote:
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
        hit = (
            not in_quote
            and depth == 0
            and cond[i:i + len(kw)].lower() == kw
            and (i == 0 or cond[i - 1].isspace())
            and (i + len(kw) >= n or cond[i + len(kw)].isspace())
        )
        if hit:
            parts.append(''.join(cur))
            cur = []
            i += len(kw)
            continue
        cur.append(ch)
        i += 1
    parts.append(''.join(cur))
    return parts
def combine_conds(item_cond, group_cond):
    # MSBuild ANDs an item's Condition with its ItemGroup's: a file
    # with its own Condition inside a gated group (e.g.
    # NativeLibrary.Windows.cs with `'$(FeatureMono)' != 'true'`
    # inside the `TargetsWindows` group) is out when EITHER is false.
    # `or`-chaining here leaked Windows-only files into Linux builds.
    if item_cond and group_cond:
        return f"({item_cond}) And ({group_cond})"
    return item_cond or group_cond
def local(tag):
    return tag.rsplit('}', 1)[-1]
proj, projdir = sys.argv[1], sys.argv[2]
srcroot = sys.argv[3] if len(sys.argv) > 3 else 'src'
def flag_value(txt, kind):
    # <EnableDefaultItems>/EnableDefaultCompileItems> value in a file
    # (True/False/None when absent). Case-insensitive, like MSBuild.
    m = re.search(r'<\s*' + kind + r'\s*>\s*(true|false)\s*<', txt, re.IGNORECASE)
    if not m:
        return None
    return m.group(1).lower() == 'true'
def defaults_off(proj, start):
    # Whether SDK default globs are OFF (explicit-list only).
    # Precedence (MSBuild import order): the project file's own
    # setting first (e.g. Nrbf's `<EnableDefaultItems>true`), then
    # Directory.Build.props walking up, nearest wins (libraries/
    # sets false globally; shims/ re-enables true for its subtree).
    # SDK default with nothing found: globs ON (False).
    # Explicit-list mode prunes unlisted on-disk sources (an unlisted
    # file like HMACShared.cs — an other-target alternative to the
    # listed HMACStatic.cs — would otherwise duplicate types); glob
    # mode keeps everything not explicitly excluded.
    try:
        with open(proj, 'r', errors='ignore') as f:
            txt = f.read()
    except OSError:
        txt = ''
    items = flag_value(txt, 'EnableDefaultItems')
    comp = flag_value(txt, 'EnableDefaultCompileItems')
    if items is False or comp is False:
        return True
    if items is True and comp is not False:
        return False
    d = os.path.normpath(start)
    for _ in range(6):
        for name in ('Directory.Build.props', 'Directory.Build.targets'):
            try:
                with open(os.path.join(d, name), 'r', errors='ignore') as f:
                    txt = f.read()
            except OSError:
                continue
            items = flag_value(txt, 'EnableDefaultItems')
            comp = flag_value(txt, 'EnableDefaultCompileItems')
            if items is False or comp is False:
                return True
            if items is True and comp is not False:
                return False
        parent = os.path.dirname(os.path.abspath(d))
        if parent == os.path.abspath(d):
            break
        d = parent
    return False
explicit = defaults_off(proj, projdir)
try:
    root = ET.parse(proj).getroot()
except Exception:
    sys.exit(0)
# Local-source verdicts by resolved .rc path: a file is deleted only
# when NO entry includes it (see walk below).
decisions = {}
# Hook-generated files (sibling fetches, ThisAssembly templates, SR
# parts): staged deliberately. Tracked so the reference-assembly
# fallback below can tell "real sources" from "generated ones" — a
# library staging ONLY generated files (e.g. AccessControl's
# SR.Strings.rc, whose real sources are all Windows-gated) still
# needs its ref/*.cs API surface.
generated = set()
def resolve_import(inc, curdir):
    # Resolve an <Import Project="..."> to a filesystem path (or None
    # when unresolvable): `$(CommonPath)` is libraries/Common/src/
    # (one level up from the lib dir, like the fetch below);
    # `$(MSBuildThisFileDirectory)` is the importing file's dir.
    p = inc.replace('\\', '/')
    if '$(CommonPath)' in p:
        tail = p.split('$(CommonPath)', 1)[1].lstrip('/')
        return os.path.normpath(os.path.join('../Common/src', tail))
    if '$(MSBuildThisFileDirectory)' in p:
        tail = p.split('$(MSBuildThisFileDirectory)', 1)[1].lstrip('/')
        return os.path.normpath(os.path.join(curdir, tail))
    if '$(' in p:
        return None
    return os.path.normpath(os.path.join(curdir, p))
def fetch_to(link, tail, src, sub):
    link = (link or '').replace('\\', '/')
    dest = os.path.normpath(os.path.join('src', sub, link if link else tail))
    # Collision: a committed local source already occupies this dest
    # (e.g. Odbc's local `Common\System\Data\ProviderBase\*.cs` partials
    # vs fetched Links staged under `src/Common/`). MSBuild compiles BOTH
    # (different identities — Link vs Include path), so the fetch must
    # land elsewhere: drop the `sub` prefix and stage at the Link itself
    # (the MSBuild identity). If THAT collides too, last-wins as before
    # (genuinely ambiguous — vanishingly rare, and loud below).
    local_cs = os.path.splitext(dest)[0] + '.cs'
    if os.path.isfile(local_cs):
        alt = os.path.normpath(os.path.join('src', link if link else tail))
        if not os.path.isfile(os.path.splitext(alt)[0] + '.cs'):
            dest = alt
        else:
            print('[rubyc] warning: fetch dest %s collides twice; last-wins' % dest)
    dest = os.path.splitext(dest)[0] + '.rc'
    # A fetch happens BECAUSE a csproj entry included it: record an
    # explicit keep so explicit-list pruning (which exempts only
    # `src/Common/` and `src/CoreCLR/`) never drops a redirected fetch
    # staged outside those dirs. (Not `generated`: fetched files count
    # as real staged sources for the ref-fallback emptiness scan.)
    decisions[os.path.normpath(dest)] = True
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(src, 'rb') as fsrc, open(dest, 'wb') as fdst:
        fdst.write(fsrc.read())
def link_of(child):
    # `<Link>` arrives as an attribute (`Link="..."`) or a child
    # element (`<Link>...</Link>`); both forms occur across the
    # library projects.
    link = child.get('Link') or ''
    if not link:
        for sub in child:
            if local(sub.tag) == 'Link' and sub.text:
                link = sub.text
                break
    return link.replace('\\', '/')
custom_props = {}
def harvest_props(group, inherited_cond):
    # MSBuild lets a project define its own path shorthands
    # (`<XmlSources>System\Xml</XmlSources>`, then
    # `<Compile Include="$(XmlSources)\Foo.cs" />`, as in
    # DataContractSerialization). Without expansion those entries look
    # unresolvable and their files silently drop out of the build.
    # Collect simple unconditional values only — anything with `$`,
    # `[`, `]` or `;` (references, functions, lists) stays out.
    # Later definitions win, like MSBuild.
    gcond = combine_conds(group.get('Condition'), inherited_cond)
    if gcond and not eval_cond(gcond):
        return
    for prop in group:
        if len(list(prop)):
            continue
        name = local(prop.tag)
        if not name:
            continue
        val = (prop.text or '').strip().replace('\\', '/')
        if not val or any(c in val for c in '$[];'):
            continue
        custom_props[name] = val
def walk(node, inherited_cond, curdir, is_import, depth):
    # One project per process: a fresh document root resets the custom
    # property table (imported roots add to it, in visit order).
    if depth == 0 and not is_import and local(node.tag) == 'Project':
        custom_props.clear()
    # MSBuild: a <Compile> inherits its <ItemGroup>'s Condition when
    # it carries none of its own; when it carries one, the two AND
    # together (see combine_conds) — the group gate alone decides
    # files like the entire WasiHttpHandler group under
    # `TargetPlatformIdentifier == 'wasi'`.
    for child in node:
        tag = local(child.tag)
        if tag == 'PropertyGroup':
            # Custom path shorthands (`<XmlSources>...`), harvested in
            # document order so use-before-define stays empty, as in
            # MSBuild evaluation.
            harvest_props(child, inherited_cond)
            continue
        if tag == 'Import' and depth < 4:
            # Shared build files (`*.projitems`, `*.targets`): their
            # <Compile> entries join the importing project (e.g.
            # Crypto's AsnWriter extensions). The import's own
            # Condition gates everything inside.
            imp = child.get('Project') or ''
            icond = combine_conds(child.get('Condition'), inherited_cond)
            if icond and not eval_cond(icond):
                continue
            ipath = resolve_import(imp, curdir)
            if not ipath:
                continue
            try:
                iroot = ET.parse(ipath).getroot()
            except Exception:
                continue
            walk(iroot, icond, os.path.dirname(ipath), True, depth + 1)
        elif tag == 'Compile':
            inc = child.get('Include') or ''
            # Expand harvested custom shorthands first (`$(XmlSources)`
            # -> `System/Xml`); known `$(...)` (CommonPath and friends)
            # pass through to the dispatch below untouched.
            if '$(' in inc:
                for _pn, _pv in custom_props.items():
                    if '$(' + _pn + ')' in inc:
                        inc = inc.replace('$(' + _pn + ')', _pv)
            cond = combine_conds(child.get('Condition'), inherited_cond)
            if '$(CommonPath)' in inc:
                # Shared source: fetch when included (true or absent).
                if cond and not eval_cond(cond):
                    continue
                tail = inc.replace('\\', '/').split('$(CommonPath)', 1)[1].lstrip('/')
                src = os.path.normpath(os.path.join('../Common/src', tail))
                if not os.path.isfile(src):
                    continue
                fetch_to(child.get('Link'), tail, src, 'Common')
            elif '$(LibrariesProjectRoot)' in inc:
                # Cross-library linked source (e.g. CoreLib compiling
                # System.Reflection.Metadata's TypeName.cs): fetch when
                # included. `$(LibrariesProjectRoot)` is src/libraries/
                # (one level up from the lib dir); the `<Link>` already
                # carries the `Common/...` prefix used below `src/`.
                if cond and not eval_cond(cond):
                    continue
                tail = inc.replace('\\', '/').split('$(LibrariesProjectRoot)', 1)[1].lstrip('/')
                src = os.path.normpath(os.path.join('../', tail))
                if not os.path.isfile(src):
                    continue
                link = (child.get('Link') or '').replace('\\', '/')
                dest = os.path.normpath(os.path.join(
                    'src', link if link else tail))
                dest = os.path.splitext(dest)[0] + '.rc'
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                with open(src, 'rb') as fsrc, open(dest, 'wb') as fdst:
                    fdst.write(fsrc.read())
                decisions[dest] = True
            elif '$(CoreLibSharedDir)' in inc:
                # CoreLib shared source (e.g. Resources.Extensions
                # compiling System.Private.CoreLib's dual-use
                # ResourceReader.cs, which declares the library's own
                # partial class under RESOURCES_EXTENSIONS): fetch when
                # included. `$(CoreLibSharedDir)` is
                # src/libraries/System.Private.CoreLib/src/ (one level
                # up from the lib dir, then down). Staged at the Link
                # with an explicit keep, like fetch_to above, so
                # explicit-list pruning never drops it.
                if cond and not eval_cond(cond):
                    continue
                tail = inc.replace('\\', '/').split('$(CoreLibSharedDir)', 1)[1].lstrip('/')
                src = os.path.normpath(os.path.join('../System.Private.CoreLib/src', tail))
                if not os.path.isfile(src):
                    continue
                link = (child.get('Link') or '').replace('\\', '/')
                dest = os.path.normpath(os.path.join(
                    'src', link if link else tail))
                dest = os.path.splitext(dest)[0] + '.rc'
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                with open(src, 'rb') as fsrc, open(dest, 'wb') as fdst:
                    fdst.write(fsrc.read())
                decisions[dest] = True
            elif is_import and '$(MSBuildThisFileDirectory)' in inc:
                # Shared item from an imported file (e.g. the AsnWriter
                # extensions): fetch into the unit at its Link, like
                # the linked sources above (it lives outside srcdir,
                # so a local verdict cannot stage it).
                if cond and not eval_cond(cond):
                    continue
                tail = inc.replace('\\', '/').split('$(MSBuildThisFileDirectory)', 1)[1].lstrip('/')
                src = os.path.normpath(os.path.join(curdir, tail))
                if not os.path.isfile(src):
                    continue
                link = link_of(child)
                dest = os.path.normpath(os.path.join(
                    'src', link if link else tail))
                dest = os.path.splitext(dest)[0] + '.rc'
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                with open(src, 'rb') as fsrc, open(dest, 'wb') as fdst:
                    fdst.write(fsrc.read())
                if not link:
                    # No Link: keep the fetched copy explicitly, or
                    # explicit-list pruning drops it as unlisted.
                    decisions[dest] = True
                generated.add(dest)
            else:
                # Local source: a file listed under several differently-gated
                # groups (e.g. `Shake256.NonWindows.cs` under both the
                # browser-excluded AND the OpenSSL-included groups) is in
                # iff ANY entry includes it — record the verdict, apply
                # after the walk (first-false-wins would wrongly drop it).
                # An unconditional entry (no Condition anywhere up the
                # tree) is always in.
                if not inc:
                    continue
                p = inc.replace('\\', '/')
                p = p.replace('$(MSBuildThisFileDirectory)', './')
                if '$(' in p:
                    continue
                # Glob entry (`System\Net\Quic\**\*.cs`, often with an
                # `Exclude`): expand against the entry's directory and
                # record every match, minus excludes. Without this the
                # literal `**` path matches nothing and explicit-list
                # pruning drops the whole group (Net.Quic enums went
                # missing downstream).
                if '*' in p or '?' in p:
                    import glob as _glob
                    verdict = (not cond) or eval_cond(cond)
                    matches = set()
                    for pat in p.split(';'):
                        pat = pat.strip()
                        if not pat:
                            continue
                        base = os.path.normpath(curdir) if curdir else '.'
                        for hit in _glob.glob(os.path.join(base, pat), recursive=True):
                            if not hit.endswith('.cs'):
                                continue
                            rc = os.path.splitext(os.path.normpath(hit))[0] + '.rc'
                            # Only sources under srcdir stage (copy-all
                            # covers src/ alone; elsewhere needs a fetch,
                            # like the sibling-dir branch below).
                            if rc.startswith('src/'):
                                matches.add(rc)
                    for xp in (child.get('Exclude') or '').replace('\\', '/').split(';'):
                        xp = xp.strip()
                        if not xp:
                            continue
                        base = os.path.normpath(curdir) if curdir else '.'
                        for hit in _glob.glob(os.path.join(base, xp), recursive=True):
                            rc = os.path.splitext(os.path.normpath(hit))[0] + '.rc'
                            matches.discard(rc)
                    for rc in matches:
                        decisions[rc] = decisions.get(rc, False) or verdict
                    continue
                cs = os.path.normpath(os.path.join(projdir, p))
                # Sibling-dir include (`..\Common\JsonNamingPolicy.cs`,
                # `..\gen\...`): the file lives OUTSIDE srcdir, so the
                # copy-all above never stages it — yet MSBuild compiles
                # it and its types come out unknown downstream. Fetch it
                # into src/ at its Link (display-only upstream), like the
                # $(CommonPath) sources above.
                if cs != 'src' and not cs.startswith('src/'):
                    if cond and not eval_cond(cond):
                        continue
                    if not os.path.isfile(cs):
                        continue
                    link = link_of(child)
                    tail = link if link else p.replace('../', '')
                    dest = os.path.normpath(os.path.join('src', tail))
                    dest = os.path.splitext(dest)[0] + '.rc'
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    with open(cs, 'rb') as fsrc, open(dest, 'wb') as fdst:
                        fdst.write(fsrc.read())
                    continue
                rc = os.path.splitext(cs)[0] + '.rc'
                decisions[rc] = (decisions.get(rc, False)
                                 or (not cond) or eval_cond(cond))
        else:
            walk(child, combine_conds(child.get('Condition'), inherited_cond), curdir, is_import, depth)
walk(root, None, projdir, False, 0)
# Generated sources: MSBuild templates (`*.cs.in`, e.g.
# DiagnosticSource's `ThisAssembly.cs.in`) never exist as `.cs`, so
# copy-all misses them and their types come out unknown downstream
# (`ThisAssembly.AssemblyFileVersion`). Render each template straight
# to its `.rc` (no intermediate `.cs`, so nothing extra to clean):
# `${AssemblyFileVersion}`/`${AssemblyVersion}` are `1.0.0.0` (all
# versions are 1), `${AssemblyName}` the library dir name, anything
# else empty.
for dp, _, fns in os.walk(projdir):
    for fn in fns:
        if not fn.endswith('.cs.in'):
            continue
        tpl = os.path.join(dp, fn)
        try:
            with open(tpl, 'r', errors='ignore') as f:
                text = f.read()
        except OSError:
            continue
        libname = os.path.basename(os.path.abspath('.'))
        text = text.replace('${AssemblyFileVersion}', '1.0.0.0')
        text = text.replace('${AssemblyVersion}', '1.0.0.0')
        text = text.replace('${AssemblyName}', libname)
        text = re.sub(r'\$\{[A-Za-z0-9_.]+\}', '', text)
        base = tpl[:-len('.in')]
        gen_rc = os.path.splitext(base)[0] + '.rc'
        os.makedirs(os.path.dirname(gen_rc), exist_ok=True)
        with open(gen_rc, 'w') as f:
            f.write(text)
        decisions[gen_rc] = True
        generated.add(gen_rc)
# Generated sources, part 1b: `ThisAssembly` from
# `GenerateThisAssemblyCs.targets`. Some libraries (currently only
# XmlSerializer.Generator) embed the class text in a `.targets`
# `<ThisAssemblyCsContents>` property instead of a `.cs.in` file.
# URL-decode (`%3B` = `;`), substitute versions (`1`, like above;
# `PreReleaseLabel` is empty), and emit next to the `.targets`.
for dp, _, fns in os.walk(projdir):
    for fn in fns:
        if fn != 'GenerateThisAssemblyCs.targets':
            continue
        tpl = os.path.join(dp, fn)
        try:
            with open(tpl, 'r', errors='ignore') as f:
                text = f.read()
        except OSError:
            continue
        m = re.search(r'<ThisAssemblyCsContents>(.*?)</ThisAssemblyCsContents>', text, re.S)
        if not m:
            continue
        body = m.group(1)
        body = re.sub(r'%([0-9A-Fa-f]{2})', lambda mm: chr(int(mm.group(1), 16)), body)
        body = body.replace('$(PackageVersion)', '1.0.0.0')
        body = body.replace('$(AssemblyVersion)', '1.0.0.0')
        body = body.replace('$(AssemblyFileVersion)', '1.0.0.0')
        body = body.replace('$(PreReleaseLabel)', '')
        body = re.sub(r'\$\{[A-Za-z0-9_.]+\}', '', body)
        body = re.sub(r'\$\([A-Za-z0-9_.]+\)', '', body)
        dest = os.path.normpath(os.path.join(dp, 'ThisAssembly.rc'))
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, 'w') as f:
            f.write(body)
        decisions[os.path.normpath(dest)] = True
        generated.add(os.path.normpath(dest))
# Generated sources, part 2: `SR` from `*.resx`. dotnet generates
# `namespace System { internal static partial class SR { public static
# string <Name> => "<value>"; } }` per resx at build time; nothing
# checks it in (except CoreLib's hand-written part, also `partial`,
# which merges). Without it every `SR.X` use types as `object` —
# usually harmless (object accepts reference params) but fatal for
# value-typed params (`CheckError(bool, ...)` in Xml serialization:
# `unknown call`). Emit real strings (correct types AND values) as
# `src/Resources/SR.<base>.rc` with `decisions=True` so explicit-list
# pruning keeps them (same mechanism as the templates above — fresh
# every run, so no stage/delete oscillation). Non-string entries
# (`type=`/`mimetype=` binary blobs) are skipped; `partial` merges
# multiple resx files per library.
# Two passes: first collect every resx's properties, then write. The
# `GetResourceString` lookup (Microsoft.CSharp's ErrorFacts, and any
# future caller) is emitted ONCE, in the first file, switching over
# ALL resx properties — once per file would duplicate the method
# across partials. A resx key literally named `GetResourceString`
# would collide with the method, so it is skipped as a property.
sr_collected = []
for dp, _, fns in os.walk(projdir):
    for fn in fns:
        if not fn.endswith('.resx'):
            continue
        resx = os.path.join(dp, fn)
        try:
            rroot = ET.parse(resx).getroot()
        except Exception:
            continue
        props = []
        for data in rroot.iter('data'):
            nm = data.get('name') or ''
            if (not nm or not nm[0].isalpha() and nm[0] != '_'
                    or not all(c.isalnum() or c == '_' for c in nm)):
                continue
            if nm == 'GetResourceString':
                continue
            if data.get('type') or data.get('mimetype'):
                continue
            vel = data.find('value')
            if vel is None:
                continue
            # ET already XML-decoded the <value> text (comments live in
            # <comment>, never merged here); re-escape for a C# literal.
            val = vel.text or ''
            esc = (val.replace('\\', '\\\\').replace('"', '\\"')
                   .replace('\r', '\\r').replace('\n', '\\n').replace('\t', '\\t'))
            esc = ''.join(c if ord(c) >= 32 else '\\u%04x' % ord(c) for c in esc)
            props.append((nm, esc))
        if not props:
            continue
        rel = os.path.relpath(dp, projdir)
        dest = os.path.normpath(os.path.join('src', rel, 'SR.' + fn[:-len('.resx')] + '.rc'))
        sr_collected.append((dest, props))
sr_all_props = [(nm, esc) for _, props in sr_collected for nm, esc in props]
for _idx, (_dest, _props) in enumerate(sr_collected):
    _lines = ['        public static string %s => "%s";' % (nm, esc) for nm, esc in _props]
    if _idx == 0:
        # Lookup over every resx's strings (faithful values, not just
        # the fallback): unknown keys yield the caller's default, like
        # upstream's missing-resource path.
        _lines.append('        internal static string? GetResourceString(string resourceKey, string? defaultString)')
        _lines.append('        {')
        _lines.append('            switch (resourceKey)')
        _lines.append('            {')
        for _nm, _esc in sr_all_props:
            _lines.append('                case "%s": return %s;' % (_nm, _nm))
        _lines.append('                default: return defaultString;')
        _lines.append('            }')
        _lines.append('        }')
    os.makedirs(os.path.dirname(_dest), exist_ok=True)
    with open(_dest, 'w') as f:
        f.write('namespace System\n{\n    internal static partial class SR\n    {\n'
                + '\n'.join(_lines) + '\n    }\n}\n')
    decisions[_dest] = True
    generated.add(_dest)
# Apply local-source verdicts now that every entry has voted.
for rc, keep in decisions.items():
    if not keep and os.path.isfile(rc):
        os.remove(rc)
# Reference-assembly fallback: a library with NO staged sources on
# this platform (Windows-only `src`, e.g. System.Security.AccessControl
# whose ItemGroups gate on `TargetPlatformIdentifier == 'windows'`)
# still exposes its public API — downstream files reference those
# types unconditionally (`RegistryKey.GetAccessControl` takes an
# `AccessControlSections`). The `ref/*.cs` sources ARE that API
# surface (partial classes with `{ throw null; }` bodies, compilable
# as-is); stage them so the names resolve. Without this the lib is
# skipped and every consumer fails (`unknown name ...`).
staged = []
for dp, _, fns in os.walk(srcroot):
    for fn in fns:
        if fn.endswith('.rc') and os.path.normpath(os.path.join(dp, fn)) not in generated:
            staged.append(fn)
            break
    if staged:
        break
if not staged:
    import glob as _refglob
    for refcs in sorted(_refglob.glob(os.path.join('ref', '*.cs'))):
        dest = os.path.join(srcroot, 'ref', os.path.basename(refcs)[:-len('.cs')] + '.rc')
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(refcs, 'rb') as fsrc, open(dest, 'wb') as fdst:
            fdst.write(fsrc.read())
        decisions[os.path.normpath(dest)] = True
if explicit and os.path.basename(os.path.abspath('.')) != 'System.Private.CoreLib':
    # No SDK globs: drop staged sources with no explicit entry at all
    # (e.g. HMACShared.cs, an unlisted other-target alternative whose
    # types duplicate the listed HMACStatic.cs). Fetched Common links
    # and staged CoreCLR masters keep their own staging judgment.
    # System.Private.CoreLib is exempt: its only in-tree listing
    # (System.Private.CoreLib.Shared.projitems) is a shared fragment,
    # not the complete implementation project (real CoreLib compiles
    # via src/coreclr), so pruning drops legitimate implementation
    # files (e.g. System/Numerics/Hashing/HashHelpers.cs, needed
    # downstream by Microsoft.CSharp). CoreLib originally built with
    # everything staged and succeeded, so glob mode is its proven
    # state.
    for dp, _, fns in os.walk(srcroot):
        rel = os.path.normpath(dp)
        if rel.endswith('/Common') or '/Common/' in rel + '/':
            continue
        if rel.endswith('/CoreCLR') or '/CoreCLR/' in rel + '/':
            continue
        # Reference-assembly fallback output (`src/ref/*.rc`): staged
        # deliberately with no Compile entry — never drop it, or the
        # stage/delete cycle oscillates (run N stages it, run N+1 sees
        # the leftover, skips the fallback, then prunes it → zero
        # sources and a skipped library).
        if rel.endswith('/ref') or '/ref/' in rel + '/':
            continue
        for fn in fns:
            if not fn.endswith('.rc'):
                continue
            rc = os.path.normpath(os.path.join(dp, fn))
            if not decisions.get(rc, False) and os.path.isfile(rc):
                os.remove(rc)
PYEOF
      done
    fi
    ;;
  postbuild)
    lib="${1:?lib name required}"; srcdir="${2:-src}"
    # Install the built shared library to the per-OS rubyc libraries dir.
    os="$(uname -s)"
    case "$os" in
      Linux)  base="${RUBYC_BASE:-${RUBYC_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/rubyc}}" ;;
      Darwin) base="${RUBYC_BASE:-$HOME/Library/Application Support/rubyc}" ;;
      *)      base="${RUBYC_BASE:-${LOCALAPPDATA:-$HOME}/rubyc}" ;;
    esac
    dyn="$base/libraries"
    sta="$base/libraries/static"
    mkdir -p "$dyn" "$sta"
    # The built artifact location is decided by the compiler (shared -> .so,
    # static -> .a). Accept the common candidates so the hook keeps working
    # as the output convention settles.
    for cand in "out/$lib.so" "$lib.so" "out/$lib" "$lib"; do
      if [ -f "$cand" ]; then
        cp -- "$cand" "$dyn/$lib.so"
        echo "[install] $lib -> $dyn/$lib.so"
        # Drop the local artifact after installing: per-lib `out/`
        # dirs otherwise accumulate every built .so (8G+ and a full
        # disk at ~60 libs). (Parity: live rc-hooks.sh postbuild.)
        rm -f -- "$cand"
        # Install the .rci sidecar next to the .so when the compiler
        # emitted one (dynamic-linking consume path reads it from the
        # install dir); then drop the local copy too.
        if [ -f "out/$lib.rci" ]; then
          cp -- "out/$lib.rci" "$dyn/$lib.rci"
          echo "[install] $lib.rci -> $dyn/$lib.rci"
          rm -f -- "out/$lib.rci"
        fi
        break
      fi
    done
    # Static archives install next to the shared libraries, under
    # `static/` (same `.rci` sidecar convention; static state duplicates
    # per linked image, it is never shared at runtime).
    for cand in "out/$lib.a" "$lib.a"; do
      if [ -f "$cand" ]; then
        cp -- "$cand" "$sta/$lib.a"
        echo "[install] $lib -> $sta/$lib.a"
        rm -f -- "$cand"
        if [ -f "out/$lib.rci" ]; then
          cp -- "out/$lib.rci" "$sta/$lib.rci"
          echo "[install] $lib.rci -> $sta/$lib.rci"
          rm -f -- "out/$lib.rci"
        fi
        break
      fi
    done
    # Delete the transient build files (restore the .cs-only tree so the
    # pull script can regenerate cleanly on update): the copied .rc
    # sources. The library's .rcp and the shared .rcs stay: rebuilds
    # need them in place.
    find "$srcdir" -name '*.rc' -print0 | xargs -0 -r rm -f
    ;;
  *)
    echo "unknown hook command: $cmd" >&2
    exit 2
    ;;
esac
HOOKS
chmod +x "$HOOKS_HELPER"

# ---------- 4. enumerate libraries ----------
# A library = src/libraries/<Lib>/src/ that contains >=1 .cs file.
libdirs=()
while IFS= read -r -d '' d; do
  libdirs+=("$d")
done < <(
  for d in "$LIBS_DIR"/*/; do
    d="${d%/}"
    [ -d "$d/src" ] || continue
    [ -n "$(find "$d/src" -name '*.cs' -print -quit 2>/dev/null)" ] || continue
    printf '%s\0' "$d"
  done | sort -z
)
[ ${#libdirs[@]} -gt 0 ] || die "no libraries found under $LIBS_DIR"

# ---------- 5. generate .rcp per library + .rcs solution ----------
: > "$SOLUTION"
printf 'solution "dotnet-runtime"\n\n' >> "$SOLUTION"

# Known library names, for resolving <ProjectReference> targets.
declare -A known_libs=()
for d in "${libdirs[@]}"; do
  known_libs[$(basename "$d")]=1
done

# Extract referenced library names from a lib's .csproj files:
# <ProjectReference Include="..."> paths point at sibling libraries
# (usually via $(LibrariesProjectRoot)<Lib>\src\<Lib>.csproj, with
# Windows backslashes). Prints one lib name per line.
project_refs() {
  local dir="$1" inc norm cand ref
  grep -rhoE '<ProjectReference Include="[^"]+"' "$dir/src" --include='*.csproj' 2>/dev/null \
    | sed -E 's/.*Include="//; s/"$//' \
    | while IFS= read -r inc; do
      norm="${inc//\\//}"
      cand="$norm"
      # Preferred: segment right after $(LibrariesProjectRoot).
      case "$norm" in
        *'$(LibrariesProjectRoot)'*) cand="${norm#*'$(LibrariesProjectRoot)'}"; cand="${cand#/}" ;;
        *) # Fallback: parent directory of a /src/ segment.
          case "$norm" in
            */src/*)
              cand="${norm%%/src/*}"
              cand="${cand##*/}"
              ;;
            *) continue ;;
          esac
          printf '%s\n' "$cand"
          continue
          ;;
      esac
      ref="${cand%%/*}"
      [ -n "$ref" ] && printf '%s\n' "$ref"
    done | sort -u
}

for d in "${libdirs[@]}"; do
  lib="$(basename "$d")"
  rcp="$d/$lib.rcp"
  # Translate project references into ruby_c entries (relative to the
  # lib dir, sorted, self/dangling refs dropped).
  refs=()
  while IFS= read -r ref; do
    [ -n "$ref" ] || continue
    [ "$ref" = "$lib" ] && continue
    [ -n "${known_libs[$ref]:-}" ] || continue
    refs+=("../$ref/$ref.rcp")
  done < <(project_refs "$d")
  # PackageReferences mapping to pulled libraries (e.g. System.Memory).
  # (Parity: regen_rcp.sh package_refs.)
  while IFS= read -r ref; do
    [ -n "$ref" ] || continue
    [ "$ref" = "$lib" ] && continue
    [ -n "${known_libs[$ref]:-}" ] || continue
    refs+=("../$ref/$ref.rcp")
  done < <(grep -rhoE '<PackageReference Include="[^"]+"' "$d/src" --include='*.csproj' 2>/dev/null \
    | sed -E 's/.*Include="//; s/"$//' | sort -u)
  # Curated framework-implicit deps (tools/framework-implicit-deps.tsv).
  # (Parity: regen_rcp.sh implicit_tsv_refs.)
  if [ -f "$SCRIPT_DIR/framework-implicit-deps.tsv" ]; then
    while IFS= read -r ref; do
      [ -n "$ref" ] || continue
      [ "$ref" = "$lib" ] && continue
      [ -n "${known_libs[$ref]:-}" ] || continue
      refs+=("../$ref/$ref.rcp")
    done < <(awk -F'\t' -v lib="$lib" '$1 == lib { print $2 }' "$SCRIPT_DIR/framework-implicit-deps.tsv" | sort -u)
  fi
  # Implicit framework reference: every library except CoreLib itself
  # compiles against System.Private.CoreLib (upstream's implicit
  # shared-framework reference; csprojs express it as
  # $(CoreLibProject), which project_refs cannot see). Sorted in below.
  if [ "$lib" != "System.Private.CoreLib" ] && [ -n "${known_libs[System.Private.CoreLib]:-}" ]; then
    refs+=("../System.Private.CoreLib/System.Private.CoreLib.rcp")
  fi
  # Same for System.Private.Uri (`System.Uri` resolves for every library
  # through facade type-forwarding, never via explicit ProjectReference;
  # 20 files, always worth including).
  if [ "$lib" != "System.Private.CoreLib" ] && [ "$lib" != "System.Private.Uri" ] && [ -n "${known_libs[System.Private.Uri]:-}" ]; then
    refs+=("../System.Private.Uri/System.Private.Uri.rcp")
  fi
  # Same for System.Runtime.Numerics (`BigInteger`, `Vector2/3/4`,
  # `Matrix4x4`, ... are used across libraries without explicit
  # ProjectReference, via the shared framework; e.g. Cbor's
  # `BigInteger.ToByteArray`). Sorted in below.
  if [ "$lib" != "System.Private.CoreLib" ] && [ "$lib" != "System.Runtime.Numerics" ] && [ -n "${known_libs[System.Runtime.Numerics]:-}" ]; then
    refs+=("../System.Runtime.Numerics/System.Runtime.Numerics.rcp")
  fi
  libslines=""
  if [ ${#refs[@]} -gt 0 ]; then
    sorted=()
    while IFS= read -r r; do sorted+=("$r"); done < <(printf '%s\n' "${refs[@]}" | sort -u)
    libslist=$(printf '"%s", ' "${sorted[@]}")
    libslist="[${libslist%, }]"
    libslines="ruby_c = $libslist"
  fi
  # Preprocessor truth for a standard linux-x64 CoreCLR build
  # (release, non-AOT): .NET runtime + CoreCLR VM symbols plus the
  # feature set the MSBuild matrix enables there. CoreLib alone
  # additionally gets SYSTEM_PRIVATE_CORELIB (its `#if` split for
  # files shared with other assemblies, e.g. `public` vs
  # `internal partial class Ascii`).
  defines_line='defines = ["TARGET_LINUX", "TARGET_UNIX", "TARGET_64BIT", "TARGET_AMD64", "TARGET_LITTLE_ENDIAN", "CORECLR", "NET", "FEATURE_PERFTRACING"]'
  if [ "$lib" = "System.Private.CoreLib" ]; then
    defines_line='defines = ["TARGET_LINUX", "TARGET_UNIX", "TARGET_64BIT", "TARGET_AMD64", "TARGET_LITTLE_ENDIAN", "CORECLR", "NET", "FEATURE_PERFTRACING", "SYSTEM_PRIVATE_CORELIB"]'
  fi
  # Harvest per-library <DefineConstants> additions (e.g. Asn1's
  # CP_NO_ZEROMEMORY, Crypto's INTERNAL_ASYMMETRIC_IMPLEMENTATIONS):
  # unconditional single-line elements in src/*.csproj only.
  extra=""
  while IFS= read -r line; do
    case "$line" in *Condition=*) continue;; esac
    content="${line#*<DefineConstants>}"; content="${content%</DefineConstants>*}"
    content="${content//\$(DefineConstants);/}"
    content="${content//;/ }"
    for tok in $content; do
      case "$tok" in *'$'*) continue;; esac
      case " $extra " in *" $tok "*) ;; *) extra="$extra $tok";; esac
    done
  done < <(grep -h "<DefineConstants>" "$d/src"/*.csproj 2>/dev/null || true)
  for tok in $extra; do
    defines_line="${defines_line%\]}, \"$tok\"]"
  done
  cat > "$rcp" <<EOF
[meta]
name = "$lib"
version = "1"
description = "Pulled from dotnet/runtime $SRC_REL/$lib ($BRANCH @ $SHA)"

[target]
platform = "linux_x86_64"
output = "shared"

[build]
sources = ["src/**/*.rc"]
entry-point = ""
$defines_line

[libs]
$libslines

[hooks]
pre-build = "bash ../rc-hooks.sh prebuild src"
post-build = "bash ../rc-hooks.sh postbuild $lib src"
EOF
  printf '[[project]]\npath = "%s/%s.rcp"\n\n' "$lib" "$lib" >> "$SOLUTION"
done

log "generated ${#libdirs[@]} projects + solution"
log "solution : $SOLUTION"
log "hooks    : $HOOKS_HELPER"
log "done."
